sandbox.pydio.com-my-files:
  __type__: JobConfig
  active: true
  direction: bi
  directory: /Users/lthibault/Pydio/My Files
  filters:
    exclude: [.*, '*/.*', /recycle_bin*, '*.pydio_dl', '*.DS_Store', .~lock.*, ~*,
      '*.xlk', '*.tmp']
    include: ['*']
  frequency: 10
  hide_bi_dir: 'false'
  hide_down_dir: 'false'
  hide_up_dir: 'false'
  id: sandbox.pydio.com-my-files
  label: Pydio Enterprise - My Files
  poolsize: 4
  remote_folder: ''
  server: http://sandbox.pydio.com/enterprise
  solve: both
  start_time: {h: 0, m: 0}
  timeout: 20
  trust_ssl: false
  user: louis
  workspace: my-files
